# Docker Compose File - Last Updated: 2023-09-06
version: '3.8'
services:
  app:
    container_name: open_management_container
    restart: on-failure
    build:
      context: ../
      dockerfile: environments/Dockerfile
    image: open_management_image
    env_file:
      - .env
    ports:
      - "${APP_LOCAL_PORT}:${APP_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.datasource.initialization-mode" : "always"
          }'
    volumes:
      - ../.m2:/root/.m2
    #   stdin_open: true
    #   tty: true
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysql_container
    restart: unless-stopped
    image: mysql:8.0
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    env_file:
      - .env
    volumes:
      - ../db:/var/lib/mysql
    #     - ${DATA_PATH}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_PASSWORD}
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}