version: '3.8'
services:
  db:
    container_name: mysql_container
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=jfecm
      - MYSQL_PASSWORD=jfecm
      - MYSQL_DATABASE=open_management_db